stages:
  - build

build-android:
  image: tafilz/xamarin-android:29
  stage: build
  only:
    - tags
  except:
    - branches
  artifacts:
    paths:
      - publish_android/*.apk
  script:
    - export BUILD_DATE=$(date +%Y%m%d%H%M%S)
    - msbuild ENSIKLO/ENSIKLO.sln /p:AndroidSdkDirectory=/usr/lib/android-sdk /p:Configuration="Release" /p:Platform="Any CPU" /restore
    - msbuild ENSIKLO/ENSIKLO.Android/ENSIKLO.Android.csproj /p:AndroidSdkDirectory=/usr/lib/android-sdk /p:Configuration="Release" /p:Platform="Any CPU" /t:PackageForAndroid /p:OutputPath="../../publish_android/"
    - msbuild ENSIKLO/ENSIKLO.Android/ENSIKLO.Android.csproj /p:AndroidSdkDirectory=/usr/lib/android-sdk /p:Configuration="Release" /p:Platform="Any CPU" /t:SignAndroidPackage /p:OutputPath="../../publish_android/"
